name: githubpages deployment

on:
  push:
    branches:
      - main


jobs:
  build:
    if: github.repository == 'decloudf/dcf-home'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build bundle
        run: yarn generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          target-folder: docs # The folder the action deploy to.
